name: BMPingTag
main: BlockMagicDev\BMPingTag\BMPingTag
api: 4.0.0
version: 1.0.0
author: BlockMagicDev
description: show player's ping number under their name

permissions:
  bmpingtag.command:
    description: Permission use command /bmpingtag
    default: op